const TASK_CHANNEL_APPLICATION = "application";
const TASK_CHANNEL_MORTGAGE_APPLICATION = "mortgage-application";
const TASK_CHANNEL_CC_DISPUTE = "credit-card-dispute";
const TASK_CHANNEL_CC_FRAUD = "credit-card-fraud";

export {
  TASK_CHANNEL_APPLICATION,
  TASK_CHANNEL_MORTGAGE_APPLICATION,
  TASK_CHANNEL_CC_DISPUTE,
  TASK_CHANNEL_CC_FRAUD,
};
